### ISSUE TITLE
Master doesn't build with ocaml-gstreamer 0.3.0

### ISSUE THREAD

**Issue by iSchluff** [savonet/liquidsoap#1398]
Hi,
Building master via opam with gstreamer produces the following error:
```
The following actions will be performed:
  - install liquidsoap 2.0.0*

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of liquidsoap failed at "/usr/bin/make".

#=== ERROR while compiling liquidsoap.2.0.0 ===================================#
# context     2.0.5 | linux/x86_64 | ocaml-base-compiler.4.08.0 | pinned(git+file:///home/liquid/liquidsoap#master#928c13cf)
# path        ~/.opam/4.08.0/.opam-switch/build/liquidsoap.2.0.0
# command     /usr/bin/make
# exit-code   2
# env-file    ~/.opam/log/liquidsoap-23945-2dea01.env
# output-file ~/.opam/log/liquidsoap-23945-2dea01.out
### output ###
# [...]
# OCAMLOPT -c encoder/lame_encoder_builtin.ml
# OCAMLOPT -c encoder/taglib_id3v2.ml
# OCAMLOPT -c encoder/gstreamer_encoder.ml
# File "encoder/gstreamer_encoder.ml", line 173, characters 10-39:
# 173 |           Gstreamer.Buffer.of_data_list
#                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound value Gstreamer.Buffer.of_data_list
# make[2]: *** [../Makefile.rules:125: encoder/gstreamer_encoder.cmx] Error 2
# make[2]: Leaving directory '/home/liquid/.opam/4.08.0/.opam-switch/build/liquidsoap.2.0.0/src'
# make[1]: *** [../Makefile.rules:67: all-auto-ocaml-prog] Error 2
# make[1]: Leaving directory '/home/liquid/.opam/4.08.0/.opam-switch/build/liquidsoap.2.0.0/src'
# make: *** [Makefile.rules:27: all-subdirs] Error 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build liquidsoap 2.0.0
+-
- No changes have been performed
```

**Installed Packages**
```
liquid@0f1b83275503:~/liquidsoap$ opam list
# Packages matching: installed
# Name                  # Installed # Synopsis
base-bigarray           base
base-bytes              base        Bytes library distributed with the OCaml compiler
base-threads            base
base-unix               base
camomile                1.0.2       A Unicode library
conf-libogg             1           Virtual package relying on libogg
conf-libpcre            1           Virtual package relying on a libpcre system installation
conf-libssl             2           Virtual package relying on an OpenSSL library system installation
conf-m4                 1           Virtual package relying on m4
conf-pkg-config         1.3         Virtual package relying on pkg-config installation
cry                     0.6.5       OCaml client for the various icecast & shoutcast source protocols
csexp                   1.3.2       Parsing and printing of S-expressions in Canonical form
ctypes                  0.17.1      Combinators for binding to C libraries without writing any C
dtools                  0.4.2       Library providing various helper functions to make daemons
dune                    2.7.1       Fast, portable, and opinionated build system
dune-configurator       2.7.1       Helper library for gathering system configuration
duppy                   0.9.0       Library providing monadic threads
ffmpeg                  0.4.3       Bindings for the ffmpeg library which provides functions for decoding audio and video files
gen                     0.5.3       Iterators for OCaml, both restartable and consumable
gstreamer               0.3.0       Bindings for the GStreamer library which provides functions for playning and manipulating multimedia streams
integers                0.4.0       Various signed and unsigned integer types for OCaml
lame                    0.3.4       MP3 encoding library
mad                     0.5.0       Mad decoding library
menhir                  20200624    An LR(1) parser generator
menhirLib               20200624    Runtime support library for parsers generated by Menhir
menhirSdk               20200624    Compile-time library for auxiliary tools related to Menhir
mm                      0.6.0       The mm library contains high-level to create and manipulate multimedia streams (audio, video, MIDI)
ocaml                   4.08.0      The OCaml compiler (virtual package)
ocaml-base-compiler     4.08.0      Official release 4.08.0
ocaml-config            1           OCaml Switch Configuration
ocaml-migrate-parsetree 1.8.0       Convert OCaml parsetrees between different versions
ocamlbuild              0.14.0      OCamlbuild is a build system with builtin rules to easily build most OCaml projects.
ocamlfind               1.8.1       A library manager for OCaml
ogg                     0.6.1       Bindings to libogg
opam-depext             1.1.4       Install OS distribution packages
pcre                    7.4.6       Bindings to the Perl Compatibility Regular Expressions library
posix-base              2.0.0       Base module for the posix bindings
posix-socket            2.0.0       Bindings for posix sockets
ppx_derivers            1.2.1       Shared [@@deriving] plugin registry
ppx_tools_versioned     5.4.0       A variant of ppx_tools based on ocaml-migrate-parsetree
result                  1.5         Compatibility Result module
sedlex                  2.2         An OCaml lexer generator for Unicode
ssl                     0.5.9       Bindings for OpenSSL
taglib                  0.3.6       Bindings for the taglib library which provides functions for reading tags in headers of audio files
uchar                   0.0.2       Compatibility library for OCaml's Uchar module
vorbis                  0.7.1       Bindings to libvorbis
```

**Version details**
 - OS: Debian Testing
 - Version git@928c13cfc199cfc03637c8db1208ba319a06120a

**Install method**
Install via opam pinning

Greets, Anton

**Comment by iSchluff** [comment]
And if LS is built without ocaml-gstreamer it fails with 
```
$ liquidsoap test.lq
At line 481, char 32-68:
Error 3: Builtin input.gstreamer.audio_video is not registered!  
```

**Comment by toots** [comment]
Yes, we need a release of `ocaml-gstreamer`. Meanwhile, you can installed a pinned version:
```
git clone https://github.com/savonet/ocaml-gstreamer.git
cd ocaml-gstreamer
opam install -y .
```

**Comment by smimram** [comment]
But still, this means that the dependencies are incorrect in the opam file doesn't it?

**Comment by toots** [comment]
That was right. Liquidsoap's opam has been updated and a `0.3.1` release is on its way to `opam`: https://github.com/ocaml/opam-repository/pull/17585

**Comment by iSchluff** [comment]
thats great, thanks :)
