### ISSUE TITLE
Problems installing from latest 2.0 - git hub -- Unbound value Avedevice.init

### ISSUE THREAD

**Issue by millicent-audio-mirror** [savonet/liquidsoap#1629]
**Describe the bug**
Liquidsoap - 2.0 does not compile with error - using ocaml ffmpeg - 1.0 and ffmpeg - 4.4

```
# path        ~/.opam/4.10.1/.opam-switch/build/liquidsoap.2.0.0
# command     /usr/bin/make
# exit-code   2
# env-file    ~/.opam/log/liquidsoap-169342-a1b48d.env
# output-file ~/.opam/log/liquidsoap-169342-a1b48d.out
### output ###
# [...]
# OCAMLOPT -c tools/unifier.mli
# OCAMLOPT -c tools/unifier.ml
# OCAMLOPT -c tools/liqavdevice.ml
# File "tools/liqavdevice.ml", line 1, characters 9-22:
# 1 | let () = Avdevice.init ()
#              ^^^^^^^^^^^^^
# Error: Unbound value Avdevice.init
# make[2]: *** [../Makefile.rules:127: tools/liqavdevice.cmx] Error 2
# make[2]: Leaving directory '/home/russ/.opam/4.10.1/.opam-switch/build/liquidsoap.2.0.0/src'
# make[1]: *** [../Makefile.rules:69: all-auto-ocaml-prog] Error 2
# make[1]: Leaving directory '/home/russ/.opam/4.10.1/.opam-switch/build/liquidsoap.2.0.0/src'
# make: *** [Makefile.rules:29: all-subdirs] Error 2
```

**To Reproduce**
opam install

**Expected behavior**
install liquidsoap

**Version details**
 - OS: [e.g. Debian, OSX] : - Arch Linux
 - Version [e.g. `1.3.4`] 2.0 - latest (10/05/2021)

**Install method**
Opam

**Common issues**
Can't decode or encode in some audio format? Check if you have [installed the correct dependencies](https://www.liquidsoap.info/#download)

**Comment by toots** [comment]
Hi! It looks like you need to update your pinned version of `ocaml-ffmpeg`.

**Comment by millicent-audio-mirror** [comment]
Arch Linux

**Comment by millicent-audio-mirror** [comment]
I just deleted my switch , installed 4.11.1.

Liquidsoap install fine on its own, and with ffmpeg (latest git pulls for both).

When i install taglib 0.3.6 (which installs fine) the above libvmaf error occurs when liquidsoap is compiled.

I also get the same error compiling LS after installing soundtouch 0.1.9.

I hope this help track things down .

Thanks

**Comment by toots** [comment]
Yeah something is off with `c++` linking. These two bindings are the ones that use it. It's been a problem in the past but we haven't seen it in a while. What's your compiler? It would seem that `gcc` should be preferred since it's the most widely used but that's really just a guess here..

**Comment by millicent-audio-mirror** [comment]
Brilliant, thank you. I had gcc8 set as default (for an old version of cuda i need), updated link to gcc10 and installation completed without issues. 

Thanks again.

Closing issue.
