### ISSUE TITLE
Fails to build on OpenBSD

### ISSUE THREAD

**Issue by werdl** [savonet/liquidsoap#4704]
### Description

Liquidsoap fails to build on OpenBSD 7.7, giving the following error:
```
#=== ERROR while compiling mem_usage.0.1.2 ====================================#
# context     2.3.0 | openbsd/x86_64 | ocaml-base-compiler.5.4.0 | https://opam.ocaml.org#5bf570252bd9fee71938b828ca0b86573c1e3355
# path        ~/.opam/5.4.0/.opam-switch/build/mem_usage.0.1.2
# command     ~/.opam/5.4.0/bin/dune build -p mem_usage -j 1 @install
# exit-code   1
# env-file    ~/.opam/log/mem_usage-61193-53e8b2.env
# output-file ~/.opam/log/mem_usage-61193-53e8b2.out
### output ###
# File "lib/dune", line 7, characters 9-18:
# 7 |   (names mem_usage)
#              ^^^^^^^^^
# (cd _build/default/lib && /usr/bin/cc -O2 -fno-strict-aliasing -fwrapv -fPIC -pthread -D_FILE_OFFSET_BITS=64 -O2 -fno-strict-aliasing -fwrapv -fPIC -pthread -g -I /home/werdl/.opam/5.4.0/lib/ocaml -o mem_usage.o -c mem_usage.c)
# mem_usage.c:204:10: fatal error: 'sys/sysinfo.h' file not found
# #include <sys/sysinfo.h>
#          ^~~~~~~
# 1 error generated.
```
`sysinfo.h` is a Linux-only library. Is this going to be fixed?

### Steps to reproduce

Follow the opam build instructions on OpenBSD 7.7.

### Expected behavior

Successful build.

### Log extracts

```
#=== ERROR while compiling mem_usage.0.1.2 ====================================#
# context     2.3.0 | openbsd/x86_64 | ocaml-base-compiler.5.4.0 | https://opam.ocaml.org#5bf570252bd9fee71938b828ca0b86573c1e3355
# path        ~/.opam/5.4.0/.opam-switch/build/mem_usage.0.1.2
# command     ~/.opam/5.4.0/bin/dune build -p mem_usage -j 1 @install
# exit-code   1
# env-file    ~/.opam/log/mem_usage-61193-53e8b2.env
# output-file ~/.opam/log/mem_usage-61193-53e8b2.out
### output ###
# File "lib/dune", line 7, characters 9-18:
# 7 |   (names mem_usage)
#              ^^^^^^^^^
# (cd _build/default/lib && /usr/bin/cc -O2 -fno-strict-aliasing -fwrapv -fPIC -pthread -D_FILE_OFFSET_BITS=64 -O2 -fno-strict-aliasing -fwrapv -fPIC -pthread -g -I /home/werdl/.opam/5.4.0/lib/ocaml -o mem_usage.o -c mem_usage.c)
# mem_usage.c:204:10: fatal error: 'sys/sysinfo.h' file not found
# #include <sys/sysinfo.h>
#          ^~~~~~~
# 1 error generated.
```

### Script extracts

N/A

### Liquidsoap version

```text
Attempting to install 2.4.1.
```

### Liquidsoap build config

```text
N/A
```

### Installation method

From OPAM
